sudo: required

language: bash

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=fiwoo/gis

script:
  - docker build -t $DOCKER_IMAGE infrastructure/docker-containers/ubuntu_16.04-tomcat/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push $DOCKER_IMAGE:latest;
      docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      curl "http://ci-system-sac-fase-dos.emergyalabs.com:8080/jenkins/job/gis-MASTER-fiwoo-deployment/build?token=$JENKINS_TOKEN";
    fi

notifications:
  email:
    recipients:
      - sac-fase-dos-dev@emergya.com
    on_success: always
    on_failure: always

